### ISSUE TITLE
Withdraw XNA

### ISSUE THREAD

**Issue by YannV22** [NeuraiProject/electrum-neurai#3]
Hello,

 I can't make a withdrawal from electrum wallet whether it's version 0.1.0 or 0.2.0? there is an error message each time I try, how to withdraw my funds. 

Sincerely.

**Comment by NeuraiProject** [comment]
Can you detail a little more? 
SO
All the steps you have followed 
Screenshot of the error 
Is the wallet synchronized?

Regards
