### ISSUE TITLE
Withdrawal Error

### ISSUE THREAD

**Issue by eljake-png** [NeuraiProject/electrum-neurai#5]
I cannot withdraw neurai coins, that I mined to this wallet. After syncing 0.2.0 wallet i tried to send, but I get this message after it tries to broadcast:
The server returned an error when broadcasting the transaction.
Consider trying to connect to a different server, or updating Electrum.

The transaction was rejected because it is too large (in bytes).

Updating to 0.2.1 didn't help as well as changing servers.
Please help @NeuraiProject 
![Screenshot (62)](https://github.com/NeuraiProject/electrum-neurai/assets/154931771/a74c12ee-61b6-4cb5-9fc7-12d3e3741c36)

**Comment by NeuraiProject** [comment]
Electrum was not created to handle as many data entries as occurs when mining this wallet. To solve this problem, you must use the words created in Electrum and restore your addresses in the Neurai-QT wallet and send from it to another address to consolidate UTXO.

More info here: https://river.com/learn/bitcoins-utxo-model/
