### ISSUE TITLE
 failed transaction/banned from discord

### ISSUE THREAD

**Issue by Tonydenicolo** [NeuraiProject/electrum-neurai#8]
Hello, good afternoon, I am using qt neurai to receive mining payments, however for a few days it has been failing and I am not receiving the payments.

I expressed my case on discord, and they expelled me, I don't understand why.

I hope you can answer me.

![Sin título2222](https://github.com/NeuraiProject/electrum-neurai/assets/163366579/ce559a04-7303-4f41-9ac9-f786fa3525bc)

thank you

**Comment by NeuraiProject** [comment]
Electrum was not created to manage very large transaction histories and what you should do is to consolidate them at a new address.

For this, it is better to use Neurai-QT and send it to a new address that has no history.
